name : print_hello
on    : [push]
jobs :
  print run-shell-command:
    runs-on: ubuntu-latest
    steps:
      name: python command
      run : |
        print("Hello world")
      shell : python 

  runs-on windows-latest:
    runs-on : windows-latest
    needs: [print run-shell-command]
    steps : 
      name : python command
      shell : python
      run : |
        import uuid
        myuuid = uuid.uuid4()
        print('Your UUID is: ' + str(myuuid))
      